spring.application.name=sunline-backend
spring.datasource.url=jdbc:mysql://localhost:3306/sunline_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Dhana123#!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.frontend.url=http://localhost:5173
